/vis/open OGL 1000x700-0+0
/vis/drawVolume
/vis/viewer/set/style surface
/vis/viewer/set/viewpointThetaPhi 90 25
/vis/viewer/zoom 1.3
/vis/scene/add/axes 0 0 0 50 mm
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
/vis/scene/add/trajectories
/vis/viewer/flush
